### ISSUE TITLE
Criação das tabelas relacionadas as medalhas

### ISSUE THREAD

**Issue by 404jv** [404jv/dev-landia#66]
Para fazer o sistema de entrega de medalhas serão preciso 3 tabelas:
![image](https://user-images.githubusercontent.com/53544964/168493331-0de09a09-630e-47b0-b948-2aa7bb889e0c.png)
_Relacionamento completo no [Lucidchart](https://lucid.app/lucidchart/baa3fd86-d248-40fc-898b-3eaa7da3ac6d/edit?viewport_loc=419%2C54%2C1735%2C770%2C0_0&invitationId=inv_4310d971-d43b-46f6-85b5-1221de03e802)_

**achievements**
- Tabela para conter as informações das medalhas
- A coluna `image_name` é opcional, ou seja, `isNullable`

**user_achievement**
- Tabela para fazer o relacionamento `many to many` entre users e achievements

**goals**
- Tem relacionamento `many to one` com achievements (um `achievement` pode ter vários `goal`)
- Tabela para conter as informações das metas que deverão ser compridas para que o usuário receba as medalhas

**objetivo**
Criar 3 migrations, cada uma para a criação de cada tabela. Primeiro a migration que cria a tabela `achievements`, depois a que cria  `user_achievement` e por fim a `goals`. Lembrando de seguir nomes bons nas migrations, recomendo: `create-table-achievements`, `create-table-user-achievement` e `create-table-goals`.

**to-do**
- [ ] migration da achievements
- [ ] migration da user_achievement
- [ ] migration da goals

**Comment by 404jv** [comment]
Fiz o relacionamento do banco, não sei se ainda é o veredito.
![image](https://user-images.githubusercontent.com/53544964/179053338-6bb58d2a-a393-4178-8aab-4c86a4f25818.png)

A lógica é a seguinte: existem um Achievement, ele pode ter sido desbloqueado por um usuário ou não (is_unlocked). Esse Achievement podem ter diversas property, isso equivale aquelas missão de jogos como "matar 3 inimigos", "convidar 5 amigos" ou "terminar 5 leveis". Ou seja, um Achievement vai ter um array de properties.

Uma Property tem nome, que vai ser usada como tag, então, algumas vão ter o mesmo nome como "completedLevels" ou "invetedFriends". Por causa que fica mais fácil de filtrar e checar se o usuário completou aquela property e está apto a ganhar o achievement. 

Com isso, o back não vai checar se o usuário convidou 5 amigos no final de uma atividade prática porque não faz sentido, né? Ele só vai checar properties cujo o nome seja "completedLevels", "completedMaps" e afins. Além disso, só vai checar as que não tiverem o `is_unlocked` como true pois também não faz sentido checar uma property de um achievement que o usuário já  tem. 

Cada property tem uma rule que diz basicamente coisas como: "ativa se maior ou igual que", "ativa de se menor que" e etc... Com isso podemos ter um valor que a gente quer alcançar como 10 ou 5, isso fica na coluna `activation_value`. Por fim, temos o value na tabela `user_properties` que é um contador do usuário. 

Portanto, se uma property for pra completar 5 levels, a gente tem: 
- um name como `completedLevels`
- a rule dele vai ser ">=" (ativa se maior ou igual que) 
- `activation_value` como 5
- `value` do usuário como 0.

conforme o usuário joga o código vai filtrando os achievements vai comprando e aumentando o value do usuário até chegar na meta esperada, quando isso acontecer com todas as properties do achievement, ele será liberado pro usuário com o `is_unlocked` como true.
